
const SUBJECTS = [
  { e: '🐶', n: 'cane', al: ['cagnolino', 'cucciolo di cane'] },
  { e: '🐱', n: 'gatto', al: ['gattino', 'micio'] },
  { e: '🦁', n: 'leone', al: [] },
  { e: '🐯', n: 'tigre', al: [] },
  { e: '🐼', n: 'panda', al: [] },
  { e: '🐨', n: 'koala', al: [] },
  { e: '🦊', n: 'volpe', al: [] },
  { e: '🐻', n: 'orso', al: [] },
  { e: '🐸', n: 'rana', al: [] },
  { e: '🐵', n: 'scimmia', al: ['scimmietta'] },
  { e: '🦄', n: 'unicorno', al: [] },
  { e: '🐷', n: 'maiale', al: ['porcellino'] },
  { e: '🐮', n: 'mucca', al: ['vacca'] },
  { e: '🐔', n: 'gallina', al: ['pollo'] },
  { e: '🦉', n: 'gufo', al: [] },
  { e: '🐢', n: 'tartaruga', al: [] },
  { e: '🐍', n: 'serpente', al: [] },
  { e: '🐙', n: 'polpo', al: [] },
  { e: '🦈', n: 'squalo', al: [] },
  { e: '🐬', n: 'delfino', al: [] },
  { e: '🍕', n: 'pizza', al: [] },
  { e: '🍔', n: 'hamburger', al: ['panino'] },
  { e: '🍟', n: 'patatine', al: ['patatine fritte'] },
  { e: '🌮', n: 'taco', al: [] },
  { e: '🍩', n: 'ciambella', al: ['donut'] },
  { e: '🍦', n: 'gelato', al: ['gelato al cono'] },
  { e: '🍰', n: 'torta', al: ['fetta di torta'] },
  { e: '🍫', n: 'cioccolato', al: ['cioccolata'] },
  { e: '🍎', n: 'mela', al: [] },
  { e: '🍌', n: 'banana', al: [] },
  { e: '🍇', n: 'uva', al: [] },
  { e: '🍉', n: 'anguria', al: ['cocomero'] },
  { e: '⚽', n: 'pallone', al: ['pallone da calcio', 'calcio'] },
  { e: '🏀', n: 'basket', al: ['pallacanestro'] },
  { e: '🎸', n: 'chitarra', al: [] },
  { e: '🎹', n: 'pianoforte', al: ['piano'] },
  { e: '🎧', n: 'cuffie', al: [] },
  { e: '📷', n: 'macchina fotografica', al: ['fotocamera', 'camera'] },
  { e: '🚗', n: 'macchina', al: ['auto', 'automobile'] },
  { e: '✈️', n: 'aereo', al: ['aeroplano'] },
  { e: '🚀', n: 'razzo', al: ['astronave'] },
  { e: '🚲', n: 'bicicletta', al: ['bici'] },
  { e: '⛵', n: 'barca a vela', al: ['barca', 'veliero'] },
  { e: '🏰', n: 'castello', al: [] },
  { e: '🗼', n: 'torre', al: ['torre eiffel'] },
  { e: '🌋', n: 'vulcano', al: [] },
  { e: '🏝️', n: 'isola', al: ['isola tropicale'] },
  { e: '🌈', n: 'arcobaleno', al: [] },
  { e: '⭐', n: 'stella', al: [] },
  { e: '🌙', n: 'luna', al: [] },
  { e: '☀️', n: 'sole', al: [] },
  { e: '⚡', n: 'fulmine', al: ['saetta'] },
  { e: '🔥', n: 'fuoco', al: ['fiamma'] },
  { e: '❄️', n: 'neve', al: ['fiocco di neve'] },
  { e: '🌸', n: 'fiore', al: ['fiore di ciliegio'] },
  { e: '🌵', n: 'cactus', al: [] },
  { e: '🍄', n: 'fungo', al: [] },
  { e: '👑', n: 'corona', al: [] },
  { e: '💎', n: 'diamante', al: ['gemma'] },
  { e: '🎁', n: 'regalo', al: ['pacco regalo'] },
  { e: '🎈', n: 'palloncino', al: [] },
  { e: '🎉', n: 'coriandoli', al: ['festa'] },
  { e: '🕹️', n: 'joystick', al: ['videogioco'] },
  { e: '🎲', n: 'dado', al: [] },
  { e: '🃏', n: 'jolly', al: ['carta jolly'] },
  { e: '🧩', n: 'puzzle', al: [] },
  { e: '🔑', n: 'chiave', al: [] },
  { e: '💡', n: 'lampadina', al: ['idea'] },
  { e: '⏰', n: 'sveglia', al: ['orologio'] },
  { e: '🎃', n: 'zucca', al: ['halloween', 'jack o lantern'] },
  { e: '👻', n: 'fantasma', al: [] },
  { e: '🤖', n: 'robot', al: [] },
  { e: '👽', n: 'alieno', al: [] },
  { e: '🧙', n: 'mago', al: ['stregone'] },
  { e: '🦸', n: 'supereroe', al: ['eroe'] },
  { e: '🧛', n: 'vampiro', al: [] },
  { e: '🐉', n: 'drago', al: [] },
  { e: '🦖', n: 'dinosauro', al: ['t-rex'] }
]

export default SUBJECTS
