// Soggetti per "Lo Scatto Proibito"
// Ogni soggetto: { e: emoji, n: nome, al: [alias] }
export default [
  { e: '🐶', n: 'Cane', al: ['Cane', 'Cane domestico', 'Rosspuppia'] },
  { e: '🐱', n: 'Gatto', al: ['Gatto', 'Micia', 'Gattino'] },
  { e: '🦊', n: 'Volpe', al: ['Volpe', 'Volpina'] },
  { e: '🐻', n: 'Orso', al: ['Orso', 'Ursino', 'Orsetto'] },
  { e: '🐼', n: 'Panda', al: ['Panda', 'Giant Panda', 'Pollo Panda'] },
  { e: '🐨', n: 'Koala', al: ['Koala', 'Koala morebito'] },
  { e: '🐯', n: 'Tigre', al: ['Tigre', 'Tigre dai getti', 'Felino'] },
  { e: '🦁', n: 'Leone', al: ['Leone', 'Leone re', 'Re della savana'] },
  { e: '🐘', n: 'Elefante', al: ['Elefante', 'Elefante africano', 'Trifoglio'] },
  { e: '🦏', n: 'Rinocerote', al: ['Rinocerote', 'Rinoceronte bianco', 'Rinoceronte nero'] },
  { e: '🦓', n: 'Zebra', al: ['Zebra', 'Zebra striata'] },
  { e: '🦬', n: 'Bisonte', al: ['Bisonte', 'Bufalo'] },
  { e: '🐮', n: 'Mucca', al: ['Mucca', 'Vaccia', 'Manzo', 'Rossa'] },
  { e: '🐷', n: 'Maiale', al: ['Maiale', 'Porcino', 'Maiolo', 'Verde'] },
  { e: '🐑', n: 'Pecora', al: ['Pecora', 'Agnello', 'Montone'] },
  { e: '🐏', n: 'Agnello', al: ['Agnello', 'Agnello di montagna'] },
  { e: '🦆', n: 'Anatra', al: ['Anatura', 'Anatroccoli', 'Papaya'] },
  { e: '🦅', n: 'Aquila', al: ['Aquila', 'Rapace', 'Reale'] },
  { e: '🐍', n: 'Serpente', al: ['Serpente', 'Serpente con Croce', 'Cobra'] },
  { e: '🦎', n: 'Lucertola', al: ['Lucertola', 'Gecko', 'Becco'] },
  { e: '🐢', n: 'Tartaruga', al: ['Tartaruga', 'Tartaruga marina', 'Tartarughino'] },
  { e: '🐬', n: 'Delfino', al: ['Delfino', 'Flipper', 'Tursione'] },
  { e: '🐟', n: 'Pesce', al: ['Pesce', 'Pesce giallo', 'Trota'] },
  { e: '🦈', n: 'Squalo', al: ['Squalo', 'Mako', 'Blu'] },
  { e: '⚓', n: 'Ancora', al: ['Ancora', 'Ancora navale', 'Piombincino'] },
  { e: '🎸', n: 'Chitarra', al: ['Chitarra', 'Chitarra elettrica', 'Strumento'] },
  { e: '🎹', n: 'Pianoforte', al: ['Pianoforte', 'Cembalo', 'Tastiera'] },
  { e: '🎺', n: 'Tromba', al: ['Tromba', 'Trombetta', 'Fiato'] },
  { e: '🎷', n: 'Sax contrabbasso', al: ['Sax', 'Sax contrabbasso', 'Fiato'] },
  { e: '🥁', n: 'Tamburo', al: ['Tamburo', 'Batteria', 'Percussione'] },
  { e: '🎬', n: 'Cinema', al: ['Cinema', 'Proiezione', 'Film'] },
  { e: '🎮', n: 'Videogioco', al: ['Videogioco', 'Console', 'Controller'] },
  { e: '🏓', n: 'Pallavolo da tavolo', al: ['Pallavolo da tavolo', 'Tavolino', 'Pong'] },
  { e: '🎱', n: 'Biliare', al: ['Biliare', 'Biliardo', 'Stecca'] },
  { e: '🏈', n: 'Football americano', al: ['Football americano', 'NFL', 'Palla da football'] },
  { e: '⚽', n: 'Calcio', al: ['Calcio', 'Calcio giocato', 'Palla'] },
  { e: '🏀', n: 'Basket', al: ['Basket', 'Palla da basket', 'NBA'] },
  { e: '⚾', n: 'Baseball', al: ['Baseball', 'Palla da baseball', 'MLB'] },
  { e: '🏊', n: 'Nuoto', al: ['Nuoto', 'Nuotatore', 'Stile'] },
  { e: '🏃', n: 'Corsa', al: ['Corsa', 'Corrida', 'Maratona'] },
  { e: '🚴', n: 'Ciclismo', al: ['Ciclismo', 'Bicicletta', 'Ciclista'] },
  { e: '🎯', n: 'Freccia', al: ['Freccia', 'Freccia bersaglio', 'Dardo'] },
  { e: '🎲', n: 'Dado', al: ['Dado', 'Dado da gioco', 'Dado a sei'] },
  { e: '♟️', n: 'Scacchi', al: ['Scacchi', 'Scacchiera', 'Re'] },
  { e: '🧩', n: 'Puzzle', al: ['Puzzle', 'Mappa', 'Completeness'] },
  { e: '🧱', n: 'Mattoncino', al: ['Mattoncino', 'Mattoncini', 'Blocco'] },
  { e: '🪀', n: 'Palla yo-yo', al: ['Palla yo-yo', 'Yo-yo', 'Yo-yo'] },
  { e: '🪁', n: 'Ombrelone', al: ['Ombrelone', 'Kite', 'Aquiloncchio'] },
  { e: '🔔', n: 'Campana', al: ['Campana', 'Rintocco', 'Sonagli'] },
  { e: '🪙', n: 'Moneta', al: ['Moneta', 'Monetina', 'Valuta'] },
  { e: '💍', n: 'Anello', al: ['Anello', 'Zaino', 'Oro'] },
  { e: '👑', n: 'Corona', al: ['Corona', 'Diadema', 'Re'] },
  { e: '🎩', n: 'Cappello', al: ['Cappello', 'Berretto', 'Top hat'] },
  { e: '🎓', n: 'Tassello di laurea', al: ['Tassello di laurea', 'Laurea', 'Diploma'] },
  { e: '🛏️', n: 'Letto', al: ['Letto', 'Lettino', 'Murano'] },
  { e: '🪑', n: 'Sedia', al: ['Sedia', 'Sedia da ufficio', 'Sedia da dining'] },
  { e: '🛁', n: 'Vasca', al: ['Vasca', 'Bagno', 'Bagnare'] },
  { e: '🚪', n: 'Porta', al: ['Porta', 'Porta di casa', 'Porta blindata'] },
  { e: '🪟', n: 'Finestra', al: ['Finestra', 'Finestra aperta', 'Finestra chiusa'] },
  { e: '🌮', n: 'Taco', al: ['Taco', 'Taco di carne', 'Taco vegano'] },
  { e: '🍕', n: 'Pizza', al: ['Pizza', 'Margherita', 'Diavola'] },
  { e: '🍔', n: 'Hamburger', al: ['Hamburger', 'Burger', 'Hamburger con formaggio'] },
  { e: '🍦', n: 'Gelato', al: ['Gelato', 'Gelato alla crema', 'Gelato alla vaniglia'] },
  { e: '🍰', n: 'Torta', al: ['Torta', 'Cheesecake', 'Torta di compleanno'] },
  { e: '🎂', n: 'Torta di compleanno', al: ['Torta di compleanno', 'Torta', 'Candle'] },
  { e: '🧁', n: 'Cupcake', al: ['Cupcake', 'Cupcakes', 'Muffin'] },
  { e: '🥤', n: 'Bevanda', al: ['Bevanda', 'Frullato', 'Smoothie'] },
  { e: '☕', n: 'Caffè', al: ['Caffè', 'Caffè nero', 'Espresso'] },
  { e: '🍰', n: 'Dolcetto', al: ['Dolcetto', 'Dolci', 'Dolce'] },
  { e: '📱', n: 'Smartphone', al: ['Smartphone', 'Telefono', 'Cellulare'] },
  { e: '💻', n: 'Computer', al: ['Computer', 'Laptop', 'Portatile'] },
  { e: '🖥️', n: 'Desktop', al: ['Desktop', 'Computer fisso', 'Tower'] },
  { e: '⌚', n: 'Orologio', al: ['Orologio', 'Oro', 'Tempo'] },
  { e: '🎒', n: 'Zaino', al: ['Zaino', 'Borsa', 'Valigia'] },
  { e: '🧳', n: 'Valigia', al: ['Valigia', 'Valigetta', 'Bagaglio'] },
  { e: '🚗', n: 'Auto', al: ['Auto', 'Automobile', 'Macchina'] },
  { e: '🚲', n: 'Bicicletta', al: ['Bicicletta', 'Bici', 'Bicicletta a ruote'] },
  { e: '✈️', n: 'Aereo', al: ['Aereo', 'Aereo commerciale', 'Volo'] },
  { e: '🚂', n: 'Treno', al: ['Treno', 'Locomotiva', 'Treno a vapore'] },
  { e: '🚢', n: 'Nave', al: ['Nave', 'Barca', 'Vapore'] },
    { e: '🛵', n: 'Gommetto', al: ['Gommetto', 'Barchetta', 'Moto d\'acqua'] },
  { e: '🏠', n: 'Casa', al: ['Casa', 'Casa di campagna', 'Residenza'] },
  { e: '🏢', n: 'Edificio', al: ['Edificio', 'Grattacielo', 'Ufficio'] },
  { e: '🏰', n: 'Castello', al: ['Castello', 'Fortezza', 'Forte'] },
  { e: '🗼', n: 'Torre Eiffel', al: ['Torre Eiffel', 'Torre', 'Parigi'] },
  { e: '🌇', n: 'Skyline', al: ['Skyline', 'Città', 'Veduta'] },
  { e: '🌅', n: 'Alba', al: ['Alba', 'Sorgere', 'Aurora'] },
  { e: '🌇', n: 'Tramonto', al: ['Tramonto', 'Sole', 'Ora'] },
  { e: '⭐', n: 'Stella', al: ['Stella', 'Stellina', 'Stellato'] },
  { e: '🌙', n: 'Luna', al: ['Luna', 'Luna piena', 'Notte'] },
  { e: '☁️', n: 'Nuvola', al: ['Nuvola', 'Nuvoloso', 'Pioggia'] },
  { e: '🌈', n: 'Arcobaleno', al: ['Arcobaleno', 'Arcobaletto', 'Arco'] },
  { e: '💧', n: 'Goccia', al: ['Goccia', 'Acqua', 'Pioggia'] },
  { e: '🔥', n: 'Fiamma', al: ['Fiamma', 'Fiammata', 'Bruciare'] },
  { e: '❄️', n: 'Neve', al: ['Neve', 'Gelo', 'Freddo'] },
  { e: '🍟', n: 'Patatine', al: ['Patatine', 'Patatine fritte', 'Patatine dolci'] },
  { e: '🌭', n: 'Hot dog', al: ['Hot dog', 'Hot-dog', 'Würstel'] },
  { e: '🍿', n: 'Popcorn', al: ['Popcorn', 'Pop-corn', 'Corny'] },
  { e: '🍫', n: 'Cioccolato', al: ['Cioccolato', 'Cioccolatino', 'Barrette'] },
  { e: '🎾', n: 'Tennis', al: ['Tennis', 'Racchetta', 'Field'] },
]
